#!/bin/bash -e

root=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
project_dir="$root/projects"
version=1

main() {
    cd "$root"

    if [[ $1 ]]; then
        cmd_"$1"
        return
    fi

    mkdir -p "$project_dir"

    get_project nechifor-home
    get_project circuits
    get_project check-your-privilege
    get_project pseudoromanian
    get_project sidrem
    get_project keygen-radio
    get_project papers
    get_project sibf

    process_keygen_radio

    build_docker
}

get_project() {
    local name="$1"
    local repo="https://github.com/paul-nechifor/$name"
    cd "$project_dir"

    if [[ -e "$name" ]]; then
        (cd "$name" && git pull)
    else
        git clone "$repo"
    fi
}

build_docker() {
    cd "$root"

    docker build -t nechifor-web .
    docker run --name temp_nechifor nechifor-web true
    docker export temp_nechifor | docker import - nechifor-web:"$version"
    docker rm temp_nechifor

    docker save nechifor-web:"$version" |
    xz -9 -c - > nechifor-web-"$version".tar.xz
}

cmd_run() {
    docker run -it -p 80:80 --rm nechifor-web:"$version" nginx -g 'daemon off;'
}

process_keygen_radio() {
    cd "$project_dir/keygen-radio"
    [[ -d tunes ]] || scripts/download-music-pack
    rsync -a --del tunes/files/ dist/tunes/
}

main "$@"
