#!/usr/bin/env python2

from json import load
from os import system
from os.path import dirname, join
from time import sleep
from urllib2 import urlopen


def main():
    repo_dir = join(dirname(__file__), 'repos')
    system("mkdir -p '%s'" % repo_dir)
    for repo in get_repos():
        system("""
            cd '{dir}'
            git clone --mirror '{repo}'
            cd '{name}'
            git config cgit.desc "{desc}"
            git config cgit.owner 'Paul'
        """.format(
            dir=repo_dir,
            repo=repo['clone_url'],
            name=repo['clone_url'].strip('/').split('/')[-1],
            desc=(repo['description'] or '...').replace('"', r'\"').encode('utf8'),
        ))


def get_repos():
    for i in xrange(1, 100):
        url = 'https://api.github.com/users/paul-nechifor/repos?page=%s' % i
        repos = load(urlopen(url))
        if not repos:
            return
        for x in repos:
            yield x
            sleep(2)


if __name__ == '__main__':
    main()
